@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor User
participant "<<System>> \n RobDroneGo" as sys
activate User
User -> sys: começa a criar o elevador de um edifício
activate sys
sys--> User: retorna mensagem de sucesso
deactivate sys
@enduml